# INCLUDES
include:
  - project: 'it-qa/gitlab-ci-templates'
    file: '.docu.yml'

stages:
  - build
  
workflow:
  rules:
    - if: $CI_COMMIT_REF_SLUG !~ /^staging/
      variables:
        conqa_stage: "tuap"
    - if: $CI_COMMIT_REF_SLUG =~ /^staging/
      variables:
        conqa_stage: "intd"

variables:
  # OS
  TZ: "Europe/Berlin"
  http_proxy_host: "proxy.${conqa_stage}.conqa.run"
  http_proxy_port: "3128"
  http_proxy: "http://${http_proxy_host}:${http_proxy_port}"
  java_no_proxy: "*.nicotuadev.de|*.nicotua.de|*.nicoint.de|*.comi.run|*.${conqa_stage}.conqa.run"
  no_proxy: ".nicotuadev.de,.nicotua.de,.nicoint.de,.comi.run,.${conqa_stage}.conqa.run"
  # maven
  MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
  MAVEN_CLI_OPTS: '--batch-mode --show-version --settings .mvn/settings.xml'
  # config/conqa.properties
  conqa_hostname_suffix: "-internal"
  conqa_direct_access_protocol: "http"
  conqa_direct_access_socket_protocol: "ws"
  aax4_backend_base_url: 'https://cc4.nicotuadev.de/co-restservice'

# Jobs
image:  git.congstar.net:5050/it-qa/hub/maven:3.9.8-jdk-21

compile:
  stage: build
  rules:
    - if: $coin == null
  tags:
    - external
    - $conqa_stage
  before_script:
    - 'env | sort'
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS install'
  after_script:
    - '[[ $CI_JOB_STATUS == "success" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH ]] && mvn $MAVEN_OPTS $MAVEN_CLI_OPTS deploy'
  artifacts:
    paths:
      - target/

oasdiff:
  stage: build
  image:
    name: git.congstar.net:5050/it-qa/hub/node:18-bookworm
    entrypoint: [""]
  dependencies: []
  rules:
    - if: $coin != null
  tags:
    - internal
    - $conqa_stage
  variables:
    HAS_CHANGES: 'dontknowyet'
  before_script:
    - git remote set-url --push origin "https://oauth2:$AAX4_REPO_ACCESS_TOKEN@git.congstar.net/it-qa/libs/aax4.git"
  script:
    - 'echo "AAX4 backend base url: $aax4_backend_base_url"'
    - chmod +x ./api/oasdiff/1.10.5/linux/oasdiff
    - ./api/oasdiff/1.10.5/linux/oasdiff changelog ./src/main/resources/aax4-backend/api-docs.json "${aax4_backend_base_url}/v3/api-docs" | tee ./api/api-docs-changelog.txt
    - if [[ -n $(grep '[^[:space:]]' ./api/api-docs-changelog.txt) ]]; then HAS_CHANGES = 'yes'; fi
  after_script:
    - > 
      if [[ $HAS_CHANGES == 'yes' ]]; then
        git config --global user.email "698d60a8.congstar.net@de.teams.ms"
        git config --global user.name "fnu-ci-conqa"
        git branch "auto-update/$CI_JOB_ID"
        git checkout "auto-update/$CI_JOB_ID"
        curl -s "${aax4_backend_base_url}/v3/api-docs" | json_pp > src/main/resources/aax4-backend/api-docs.json
        echo "$coin" > ../commit.txt
        cat ./api/api-docs-changelog.txt >> ../commit.txt
        git commit -a -F ../commit.txt
        git push --set-upstream origin "auto-update/$CI_JOB_ID" -o merge_request.create -o merge_request.merge_when_pipeline_succeeds -o merge_request.remove_source_branch -o merge_request.title="$coin"
      fi
  artifacts:
    when: on_failure
    paths:
      - ./api/api-docs-changelog.txt