<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.congstar</groupId>
    <artifactId>aax4-ta</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>aax4-ta</name>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <swagger.annotations.version>1.6.9</swagger.annotations.version>
        <jackson.version>2.14.1</jackson.version>
        <openapitools.jackson.nullable.version>0.2.4</openapitools.jackson.nullable.version>
        <javax.ws.rs-api.version>2.1.1</javax.ws.rs-api.version>
        <javax.annotation-api.version>1.3.2</javax.annotation-api.version>
        <findbugs.version>3.0.2</findbugs.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.13.0</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.30</version>
            <scope>provided</scope>
        </dependency>

        <!-- ====================================================== -->
        <!-- dependencies are needed for the client being generated -->
        <!-- ====================================================== -->

        <!-- Swagger annotations -->
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${swagger.annotations.version}</version>
        </dependency>

        <!-- Jackson dependencies for JSON mapping -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-base</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-json-provider</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>${openapitools.jackson.nullable.version}</version>
        </dependency>

        <!-- javax @Nullable annotation dependency not available with java 11 -->
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>${findbugs.version}</version>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>${javax.annotation-api.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- javax.ws.rs dependencies GenericType and ContextResolver -->
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>${javax.ws.rs-api.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>6.2.1</version>
                <executions>
                    <execution>
                        <id>co-restservice</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipIfSpecIsUnchanged>true</skipIfSpecIsUnchanged>
                            <generatorName>java</generatorName>
                            <library>native</library>
                            <output>target/generated-sources</output>
                            <configOptions>
                                <dateLibrary>java8-localdatetime</dateLibrary>
                                <sourceFolder>co-restservice</sourceFolder>
                            </configOptions>
                            <inputSpec>${project.basedir}/src/main/resources/aax4-backend/api-docs.json</inputSpec>
                            <apiPackage>de.congstar.congo.rest.aax4.client.api</apiPackage>
                            <invokerPackage>de.congstar.congo.rest.aax4.client.api</invokerPackage>
                            <modelPackage>de.congstar.congo.rest.aax4.client.api.model</modelPackage>

                            <!-- Source generation only -->
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateApiDocumentation>false</generateApiDocumentation>

                            <supportingFilesToGenerate>
                                AbstractOpenApiSchema.java,ApiClient.java,ApiException.java,ApiResponse.java,JSON.java,Pair.java,RFC3339DateFormat.java
                            </supportingFilesToGenerate>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>
